### ISSUE TITLE
ArchLinux 下运行报错

### ISSUE THREAD

**Issue by zxp19821005** [xushengfeng/view#1]
### 描述问题 Description of the problem

我原计划将其移植到ArchLinux的AUR，在移植运行过程中报错：
```
$ ./view 
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'split')
    at matchFitLan (/home/zxp-endeavouros/.cache/paru/clone/view-browser-bin/src/opt/view/resources/app/out/main/main.js:105:24)
    at parseLan (/home/zxp-endeavouros/.cache/paru/clone/view-browser-bin/src/opt/view/resources/app/out/main/main.js:95:10)
    at lan (/home/zxp-endeavouros/.cache/paru/clone/view-browser-bin/src/opt/view/resources/app/out/main/main.js:114:14)
    at Object.<anonymous> (/home/zxp-endeavouros/.cache/paru/clone/view-browser-bin/src/opt/view/resources/app/out/main/main.js:208:1)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at node:electron/js2c/browser_init:2:127038
```

### 重现步骤 Steps to reproduce

直接运行即可

### 操作系统 OS

ArchLinux x64

### 软件版本 Software version

126.0.0

**Comment by xushengfeng** [comment]
已在代码中更新： be1d7d3
不过现在还处于很基本的开发阶段，包括数据存储和插件等都不完善

**Comment by zxp19821005** [comment]
好的。那我等发布beta版之后再进行移植。

**Comment by xushengfeng** [comment]
我特别好奇，你是怎么发现这个没星也没issue的这个仓库的🤔
项目还未完善就被发掘并添加到aur，我还是很惊喜的😯

**Comment by zxp19821005** [comment]
额 个人爱好，喜欢移植通过electron打包的软件。你添加了`electron`的标签，然后我对这个标签按照更新日期排序，就发现了。
